In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn.metrics import accuracy_score

In [5]:
#Import dataset
dataset=pd.read_csv('train.csv',header=None)
test_data=pd.read_csv('test.csv',header=None) 

In [6]:
#Location x is independent(label) and y is independent(vales)
x=dataset.iloc[:,:1]
y=dataset.iloc[:,1:]
z=test_data


In [14]:
#Putting the first row into l and second into m
pixel=pd.DataFrame(y).to_numpy()
label=pd.DataFrame(x).to_numpy()
test_pixel=pd.DataFrame(z).to_numpy()
l=test_pixel[2]
l

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,  30, 230, 160,  70,  10,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  23, 128, 216, 238, 23

In [8]:
# Distance between first and all other rows
list1 =[]
for i in range(1,19999):
    m=pixel[i]
    q=label[i]
    distance = math.sqrt(sum([(a - b) ** 2 for a, b in zip(l,m)]))
    list1.append((q,distance))
    
for i in range(len(list1)):
    print(list1[i])

(array([2]), 2255.6287371817198)
(array([6]), 2849.868944355161)
(array([5]), 2125.253867188577)
(array([3]), 1993.8533045337113)
(array([6]), 2688.3595369667355)
(array([1]), 1749.0134361976754)
(array([1]), 2004.6989798969819)
(array([6]), 2596.7448854286786)
(array([0]), 3073.5622655153743)
(array([6]), 2316.546351791822)
(array([1]), 1702.2050405283142)
(array([9]), 2797.524441358824)
(array([5]), 2454.4133718670946)
(array([7]), 2505.4073521086348)
(array([6]), 2878.4198790308546)
(array([4]), 2741.5099853912625)
(array([6]), 2133.4483823144164)
(array([9]), 2191.052715020796)
(array([9]), 2563.8032295790563)
(array([9]), 2071.3922853964673)
(array([7]), 2287.0795788515975)
(array([7]), 2082.0324204968565)
(array([0]), 2605.460419964195)
(array([2]), 2333.1461591593443)
(array([4]), 2148.7189206594703)
(array([1]), 2650.2356498998347)
(array([8]), 2820.5242420514664)
(array([3]), 2143.3536805669755)
(array([7]), 2375.243987467393)
(array([3]), 2550.1305848916836)
(array([2]), 2752

(array([5]), 3162.372052747747)
(array([8]), 2834.5080701948973)
(array([1]), 2012.587886279752)
(array([1]), 1707.3189508700475)
(array([3]), 2394.9768266102283)
(array([1]), 1644.732805047677)
(array([0]), 2607.023782016574)
(array([1]), 1825.1851960828524)
(array([0]), 2933.1416604044202)
(array([6]), 2953.5893418009214)
(array([6]), 2252.6770740609936)
(array([6]), 2444.6459866410105)
(array([1]), 1817.1202491855072)
(array([5]), 2135.3505567002344)
(array([3]), 2254.286805178081)
(array([7]), 1491.2417644366053)
(array([3]), 2603.079138251467)
(array([9]), 2418.681252252971)
(array([8]), 2199.2396413306124)
(array([6]), 2713.452044905161)
(array([1]), 1817.7211007192495)
(array([9]), 2096.892939565585)
(array([9]), 1999.5784555750745)
(array([7]), 2227.179606587668)
(array([0]), 2688.507392587939)
(array([6]), 2073.1046765660435)
(array([0]), 2788.3502290781194)
(array([1]), 1884.063958574655)
(array([2]), 1569.3514584056688)
(array([9]), 2429.231359916136)
(array([8]), 1772.78425

(array([6]), 2255.0997760631344)
(array([7]), 1342.6842517881857)
(array([4]), 1782.1548754246921)
(array([0]), 2717.639416846908)
(array([2]), 1979.2397530365038)
(array([3]), 2597.9690144418582)
(array([0]), 2514.71230958931)
(array([0]), 2563.466793231385)
(array([1]), 1820.2796488451988)
(array([7]), 2225.523309246614)
(array([3]), 2358.719143942322)
(array([2]), 2468.4961008678947)
(array([1]), 1833.3016663931771)
(array([4]), 2904.489800291955)
(array([8]), 2419.452417387042)
(array([7]), 2169.9631333273846)
(array([4]), 1957.2294193578841)
(array([7]), 1988.2477209844853)
(array([8]), 2204.8766405402366)
(array([6]), 3051.8415751804678)
(array([1]), 1753.9977194968071)
(array([7]), 2075.9889209723638)
(array([5]), 2496.3297057880795)
(array([7]), 2523.8642990462067)
(array([3]), 1879.3025301957107)
(array([7]), 2697.8988120387316)
(array([2]), 2585.8876619064486)
(array([9]), 2347.1974778445892)
(array([1]), 1525.1432719584086)
(array([2]), 2661.919420268014)
(array([1]), 2019.2

(array([7]), 2365.1183902714047)
(array([4]), 2309.3509910795283)
(array([4]), 2169.323396822152)
(array([1]), 1935.2258266155916)
(array([3]), 2595.266845624935)
(array([2]), 2267.958112487971)
(array([7]), 1724.951303660483)
(array([6]), 2674.9340178778243)
(array([2]), 2558.3533766858714)
(array([3]), 2556.7201645858704)
(array([2]), 2306.3449438451307)
(array([8]), 2431.474861066838)
(array([7]), 1929.2441525115478)
(array([8]), 2223.7583052121468)
(array([1]), 2052.988309757267)
(array([2]), 2225.5343178661615)
(array([1]), 2005.2334028735906)
(array([3]), 1968.0840937317694)
(array([1]), 1688.0002962085048)
(array([7]), 2013.3477096616969)
(array([9]), 2385.894172003444)
(array([9]), 2279.643831829876)
(array([2]), 2113.688482250873)
(array([7]), 2373.0710061015875)
(array([2]), 2485.499145041092)
(array([9]), 2516.179842539082)
(array([7]), 1828.4868060776375)
(array([6]), 2374.591122698811)
(array([3]), 2446.5735222960293)
(array([9]), 2034.7729603078571)
(array([9]), 2661.7182

(array([3]), 1973.8832285624194)
(array([1]), 1330.4781095531034)
(array([7]), 2124.3829692407157)
(array([8]), 2207.7067287119457)
(array([3]), 2322.4842303016826)
(array([6]), 2697.296053457981)
(array([4]), 2769.1132154536404)
(array([7]), 1897.075644248273)
(array([5]), 2230.5409657748946)
(array([5]), 2957.783291588483)
(array([1]), 2033.9724678569276)
(array([5]), 2150.364155207206)
(array([1]), 1697.2371666917975)
(array([7]), 1950.0666655271045)
(array([6]), 2854.3822448999363)
(array([5]), 1942.7305525985842)
(array([2]), 2462.57020204501)
(array([4]), 2632.975313215071)
(array([4]), 2100.5556407769827)
(array([3]), 2713.7131388560583)
(array([5]), 2353.1162317233716)
(array([7]), 2422.3373010379873)
(array([3]), 2258.0310006729314)
(array([0]), 3449.368058065129)
(array([6]), 2221.8382029301774)
(array([2]), 2168.27558211589)
(array([0]), 2952.898068000316)
(array([9]), 2358.3337338044416)
(array([4]), 2125.321622719724)
(array([7]), 2472.598633017498)
(array([8]), 2484.65510

(array([7]), 2086.978916999403)
(array([4]), 1625.3199684985107)
(array([9]), 2521.1600504529656)
(array([9]), 2142.311601985108)
(array([1]), 1936.950180051103)
(array([0]), 3003.492467112245)
(array([1]), 1578.3494543351292)
(array([8]), 1981.85998496362)
(array([3]), 2205.2773068256065)
(array([9]), 2152.978169884683)
(array([7]), 2535.11715705606)
(array([6]), 2702.4668360592327)
(array([9]), 2771.2076789731946)
(array([0]), 3074.4318174257824)
(array([9]), 2171.8588812351504)
(array([8]), 2614.789284053306)
(array([4]), 2786.4821908635986)
(array([0]), 2517.8731103850328)
(array([0]), 2194.0239287665026)
(array([8]), 2063.305842573999)
(array([9]), 2331.1417803299737)
(array([3]), 2778.065693967657)
(array([8]), 1633.6199068326757)
(array([0]), 2297.390258532494)
(array([6]), 2391.6235071599376)
(array([8]), 2677.5724079845163)
(array([9]), 2652.3862840845786)
(array([2]), 2699.9544440601217)
(array([1]), 2166.1835102317623)
(array([1]), 1643.6483808892947)
(array([0]), 2895.12763

(array([5]), 2224.138035284681)
(array([0]), 3083.8326802860106)
(array([4]), 2530.4019443558764)
(array([7]), 2054.255826327383)
(array([7]), 2118.5870291305005)
(array([9]), 2571.4437578916636)
(array([7]), 2072.03474874337)
(array([1]), 1887.9549782767597)
(array([0]), 2853.6296185735105)
(array([0]), 2890.9821860398933)
(array([1]), 1946.8225394216083)
(array([7]), 1652.60491346238)
(array([3]), 2833.5327772940973)
(array([5]), 2422.538750980054)
(array([4]), 2372.506269749355)
(array([3]), 1806.5040824753207)
(array([3]), 2048.7562080442854)
(array([1]), 1939.9863401580951)
(array([7]), 1752.2850795461336)
(array([9]), 1756.6889309152034)
(array([2]), 1881.056352159605)
(array([7]), 2799.0269737892845)
(array([0]), 2750.856230339928)
(array([2]), 1861.2955165690375)
(array([8]), 2595.756537119766)
(array([1]), 1915.6424509808712)
(array([3]), 2564.2663668191726)
(array([5]), 2830.6843695474067)
(array([2]), 1731.5071469676352)
(array([4]), 2670.632509350547)
(array([6]), 2524.8805

(array([5]), 2467.2134078753706)
(array([4]), 2577.355621562535)
(array([8]), 1967.7931801894222)
(array([9]), 2365.6164101561353)
(array([4]), 1997.7054337414213)
(array([1]), 1652.3916000754784)
(array([6]), 2336.20910879142)
(array([9]), 2149.0488593794234)
(array([0]), 2692.057020198495)
(array([6]), 2663.50539702851)
(array([5]), 2435.9878899534783)
(array([4]), 3280.7098317284936)
(array([0]), 3209.3926216653517)
(array([1]), 1878.4640001873872)
(array([6]), 2853.2059161581733)
(array([9]), 2365.0429171581645)
(array([4]), 1846.4934335112052)
(array([6]), 2312.893858351481)
(array([2]), 2324.510271003335)
(array([4]), 2713.5401231601495)
(array([3]), 3137.092921798779)
(array([4]), 2165.401579384295)
(array([0]), 3119.699023944457)
(array([0]), 2922.7013189855716)
(array([4]), 2074.6059866875926)
(array([7]), 1863.5168365217417)
(array([6]), 2695.2057435379584)
(array([2]), 3035.4925465235456)
(array([8]), 2095.364884691924)
(array([7]), 2183.670762729583)
(array([2]), 1948.57127

(array([3]), 1701.623048739056)
(array([2]), 2631.4984324525067)
(array([1]), 1870.4026304515294)
(array([4]), 2366.041419755791)
(array([4]), 1998.2269640859117)
(array([5]), 2608.924682699752)
(array([1]), 1934.206555670826)
(array([1]), 1581.0521813020594)
(array([3]), 2285.470411097024)
(array([7]), 1630.5867042264265)
(array([7]), 1849.5045282453352)
(array([9]), 2142.1780971711946)
(array([6]), 2656.247164704369)
(array([9]), 2145.6726218134954)
(array([3]), 1868.0682535710519)
(array([1]), 1923.445086296981)
(array([6]), 2179.4542894954234)
(array([5]), 2475.714442337807)
(array([1]), 1900.2234079181321)
(array([1]), 2039.7494944232735)
(array([2]), 2639.988257549643)
(array([5]), 2196.6431207640444)
(array([8]), 2109.3335440370734)
(array([3]), 2449.492804643443)
(array([1]), 1531.2361019777452)
(array([9]), 2072.96164942818)
(array([6]), 3385.739210275948)
(array([9]), 2290.9336524657365)
(array([6]), 2325.4846806633664)
(array([3]), 2196.9852070507895)
(array([0]), 2189.88241

(array([9]), 3151.1164688091108)
(array([1]), 2000.540926849536)
(array([3]), 2413.2065804650874)
(array([4]), 2514.7803084961515)
(array([2]), 2397.970808829832)
(array([6]), 2696.845379327484)
(array([4]), 2068.2792364668753)
(array([2]), 3002.842986238208)
(array([4]), 2685.135750758237)
(array([8]), 1858.0971449308026)
(array([5]), 2539.066954611477)
(array([6]), 2501.588495336513)
(array([7]), 2228.5387589180496)
(array([0]), 3099.2008647391667)
(array([4]), 2740.9416265218056)
(array([6]), 2331.0304588314584)
(array([6]), 3207.3757185587097)
(array([1]), 1644.7030127047253)
(array([1]), 1926.6538350207077)
(array([2]), 2294.9542479099664)
(array([6]), 2721.0665188488133)
(array([0]), 2922.019849350788)
(array([6]), 2295.5798831667785)
(array([5]), 1945.6813716536426)
(array([2]), 2028.4821911961662)
(array([6]), 2521.6072255607137)
(array([3]), 2151.2377832308543)
(array([3]), 3119.7716262572812)
(array([2]), 2346.2798213341903)
(array([3]), 2090.8022383764564)
(array([6]), 2848.

(array([2]), 2667.9456516203622)
(array([2]), 2399.454938105736)
(array([9]), 2438.444996303997)
(array([4]), 2652.1709975037434)
(array([0]), 2960.0153715817087)
(array([0]), 2630.4986219346324)
(array([5]), 2707.358860587196)
(array([5]), 1921.4411258219702)
(array([3]), 2346.830202635035)
(array([7]), 2144.570819534762)
(array([8]), 2864.5486555476764)
(array([7]), 2119.0528544611625)
(array([2]), 2022.3872032822992)
(array([1]), 1650.4202495122265)
(array([3]), 1946.1901243198208)
(array([1]), 2123.3190998999657)
(array([6]), 2754.4578413909335)
(array([7]), 1828.535206114446)
(array([1]), 1909.0267153709506)
(array([9]), 1922.285098522069)
(array([3]), 2532.2221466530145)
(array([0]), 2568.776751685518)
(array([6]), 2935.9058227402325)
(array([5]), 2319.229613470818)
(array([7]), 2372.182539350629)
(array([8]), 2318.8115490483483)
(array([1]), 1990.9811651545074)
(array([1]), 1771.8995456853643)
(array([6]), 2122.513839766422)
(array([5]), 2669.9634828963485)
(array([9]), 2649.944

(array([1]), 1918.3164493899333)
(array([3]), 2464.4861533390686)
(array([8]), 2393.133510692623)
(array([9]), 2187.9579520639786)
(array([7]), 2408.24811844627)
(array([8]), 2483.02597650528)
(array([7]), 2096.7002647016575)
(array([5]), 2475.8616681874614)
(array([2]), 3446.9733100214166)
(array([0]), 3125.8352483776234)
(array([1]), 1992.5852553905943)
(array([3]), 2800.8207725593584)
(array([8]), 2547.6905228068813)
(array([9]), 2379.239794556236)
(array([8]), 2207.2143076738153)
(array([1]), 1819.5353802550803)
(array([5]), 2197.6580716753915)
(array([7]), 1335.8053750453319)
(array([9]), 1884.7822155357896)
(array([8]), 2315.9479700545953)
(array([4]), 2371.1562580310897)
(array([8]), 2258.4957383178744)
(array([3]), 2253.4957288621604)
(array([1]), 1780.948062128708)
(array([2]), 2486.8459944274796)
(array([4]), 2017.4374835419312)
(array([7]), 2600.790649014257)
(array([3]), 1959.0663592640244)
(array([9]), 1301.632052463368)
(array([7]), 2632.9044798473037)
(array([7]), 2858.7

(array([1]), 1744.9555868273553)
(array([7]), 1685.077446291416)
(array([6]), 2907.547764010077)
(array([5]), 2840.7954871831234)
(array([2]), 2623.473460891114)
(array([2]), 1990.5828292236422)
(array([1]), 1799.4727005431341)
(array([8]), 1960.4976409065123)
(array([3]), 2578.1113242061524)
(array([8]), 3456.912350638934)
(array([2]), 2583.414600872264)
(array([7]), 1966.566551124065)
(array([7]), 1651.7860030887778)
(array([1]), 1771.1273246155963)
(array([9]), 2921.203005612585)
(array([3]), 2655.7464110867213)
(array([5]), 2774.011535664551)
(array([3]), 2022.7248947892049)
(array([6]), 2091.524085445826)
(array([1]), 1701.9662158809147)
(array([8]), 1693.8662875209484)
(array([1]), 1812.0397346636746)
(array([6]), 2710.0123615954226)
(array([6]), 2522.587560422829)
(array([3]), 2104.928264810941)
(array([3]), 2115.5472105344284)
(array([4]), 2871.741283611739)
(array([9]), 2498.7234740963236)
(array([5]), 2429.3437385433954)
(array([1]), 1815.8939947034353)
(array([3]), 2374.8837

(array([0]), 2420.896115078051)
(array([0]), 2429.0551661088307)
(array([5]), 2226.0963591003874)
(array([8]), 3221.0388075898745)
(array([0]), 3026.0176800541003)
(array([0]), 3378.8375219888867)
(array([3]), 2730.04871751403)
(array([6]), 2172.3524115575724)
(array([7]), 2070.727649885421)
(array([7]), 1851.6033592538117)
(array([3]), 2700.3388676238396)
(array([5]), 2388.3462897997015)
(array([0]), 2637.6660137325953)
(array([3]), 2640.3895545922765)
(array([1]), 1709.2012754500272)
(array([2]), 2239.731233876065)
(array([0]), 3110.788967448612)
(array([7]), 1913.9521937603354)
(array([3]), 2567.867597832879)
(array([8]), 2440.7980252368284)
(array([5]), 2706.683764313814)
(array([8]), 2200.416551473834)
(array([3]), 2541.438568999849)
(array([1]), 1720.7338550746306)
(array([0]), 2350.666713934581)
(array([1]), 1595.6725854635717)
(array([1]), 1507.9870689100753)
(array([7]), 2832.2000282465924)
(array([1]), 1622.2179261739157)
(array([1]), 1940.883561680092)
(array([0]), 2831.5096

(array([3]), 2356.662258364571)
(array([8]), 2709.4770713183752)
(array([6]), 2351.7997363721256)
(array([3]), 2428.7288856519167)
(array([7]), 2497.9899919735467)
(array([6]), 2204.5509746884964)
(array([2]), 1964.733060748966)
(array([4]), 2179.1892987989822)
(array([2]), 2097.1075318161443)
(array([1]), 1809.917401430242)
(array([0]), 2954.1849975923988)
(array([4]), 2814.791466521099)
(array([8]), 2093.1084539507265)
(array([4]), 2256.984492636137)
(array([0]), 3148.8931388664178)
(array([8]), 1954.3515548641703)
(array([4]), 2508.6041935706)
(array([6]), 3022.0253142553256)
(array([8]), 2518.0665201697907)
(array([9]), 2006.837063640195)
(array([1]), 1822.4744168300415)
(array([8]), 2557.865907353237)
(array([0]), 3330.7159890930357)
(array([7]), 2010.0686555438847)
(array([4]), 2141.5422013119423)
(array([0]), 2931.170926438784)
(array([2]), 1971.4733069458487)
(array([9]), 2368.970451483091)
(array([6]), 2094.2327950827244)
(array([4]), 1957.5305872450626)
(array([3]), 2182.7933

(array([7]), 1713.462284382122)
(array([9]), 2413.6128521368128)
(array([1]), 1948.6656973426714)
(array([7]), 2526.3501340867224)
(array([0]), 2792.834402538038)
(array([0]), 2535.207486577775)
(array([7]), 2032.4932964219095)
(array([8]), 2432.361815191153)
(array([6]), 2079.4030393360495)
(array([7]), 1490.0157717286083)
(array([8]), 2478.3528804429766)
(array([6]), 2166.2370599728924)
(array([4]), 1928.4981202998358)
(array([2]), 2483.653760088149)
(array([1]), 1790.2055747874322)
(array([2]), 2201.0879128285633)
(array([3]), 2063.6385342399476)
(array([4]), 2403.9220037264104)
(array([4]), 1996.2211801300978)
(array([0]), 2552.1694692947017)
(array([6]), 2144.4190355431933)
(array([0]), 3023.599345151404)
(array([6]), 2123.8549856334353)
(array([3]), 2197.0004551660886)
(array([5]), 2227.1070921713667)
(array([5]), 2456.3314108645845)
(array([7]), 2535.7144949698104)
(array([6]), 2576.4089349324963)
(array([9]), 2316.63117478808)
(array([0]), 3085.5569999596505)
(array([6]), 2693.

(array([5]), 2686.784323312908)
(array([2]), 2695.1756900061264)
(array([1]), 1496.955243151912)
(array([9]), 1826.463249014335)
(array([2]), 2855.136248938043)
(array([1]), 1609.101612701945)
(array([9]), 1953.6680884940513)
(array([7]), 2165.077134884575)
(array([2]), 2957.080147713281)
(array([3]), 2512.2396382510965)
(array([3]), 2178.5942715430056)
(array([9]), 2097.570976153131)
(array([3]), 2078.741927224253)
(array([4]), 2555.6770140219205)
(array([3]), 2262.832958925603)
(array([6]), 2538.0813619740406)
(array([0]), 2958.737568626187)
(array([6]), 2511.2502862120296)
(array([0]), 3043.4345729783645)
(array([4]), 2242.3206728744217)
(array([9]), 2052.603468768383)
(array([8]), 2695.6796916547783)
(array([3]), 1898.8654507363074)
(array([9]), 1450.226534028391)
(array([9]), 2466.1603759690893)
(array([1]), 1735.7589118307876)
(array([1]), 1993.139985048717)
(array([6]), 2226.9180496821164)
(array([4]), 2794.1460233853204)
(array([9]), 2449.972244740744)
(array([7]), 1678.8201213

(array([3]), 2470.1028318675317)
(array([3]), 3040.128615700329)
(array([7]), 2186.6398880474126)
(array([2]), 2295.677024322019)
(array([8]), 1999.9269986677014)
(array([9]), 2008.308492239178)
(array([4]), 2020.0319304407046)
(array([2]), 1757.0922001989536)
(array([7]), 2329.608765436806)
(array([0]), 3093.9612150122375)
(array([7]), 1878.3077490123924)
(array([2]), 2545.283481264906)
(array([1]), 2036.2490024552499)
(array([7]), 2390.4491209812436)
(array([3]), 2318.9816730625535)
(array([4]), 1858.701697422155)
(array([7]), 1574.9469832346738)
(array([8]), 2299.7975997900335)
(array([5]), 2513.700260572052)
(array([5]), 2520.0716259662145)
(array([2]), 2326.4958628804825)
(array([4]), 2486.25682502834)
(array([4]), 2945.284536339401)
(array([5]), 2579.4960748177155)
(array([9]), 1863.0091250447488)
(array([4]), 2747.578024369827)
(array([2]), 2647.4859772999744)
(array([4]), 2809.4871418107614)
(array([4]), 1844.9203234828326)
(array([2]), 2821.8118293040025)
(array([1]), 1681.559

(array([5]), 2337.57502553394)
(array([7]), 1684.4180003787658)
(array([7]), 2012.1545666275242)
(array([2]), 2187.906076594697)
(array([4]), 1807.4432217914896)
(array([5]), 2284.309742569952)
(array([1]), 1977.0134041022584)
(array([0]), 2692.0698356469134)
(array([1]), 1743.0780246449096)
(array([1]), 1831.561628774746)
(array([1]), 1691.37784069675)
(array([1]), 1939.3911415699515)
(array([5]), 2049.124447172499)
(array([6]), 2499.4005281266946)
(array([7]), 1833.7818845217116)
(array([5]), 2435.609164049109)
(array([7]), 1875.4276845562454)
(array([5]), 2710.0068265596674)
(array([1]), 1815.6260628224084)
(array([2]), 2556.5625359063683)
(array([3]), 2255.441198524138)
(array([9]), 2337.3795156114465)
(array([2]), 2004.0538914909448)
(array([0]), 2475.6546608927506)
(array([1]), 1768.2352784626823)
(array([3]), 3106.2639939322607)
(array([3]), 2181.1233344311368)
(array([0]), 2565.567188751836)
(array([4]), 2870.7911801452924)
(array([9]), 2227.2209140541045)
(array([1]), 1793.274

(array([6]), 2710.6443883327815)
(array([4]), 2244.8022184593456)
(array([0]), 2625.148567224339)
(array([6]), 2924.0531800909503)
(array([0]), 2338.5987257329975)
(array([0]), 2917.9835503306044)
(array([1]), 1711.7967169030323)
(array([5]), 2453.9343919510156)
(array([5]), 2857.3697695608107)
(array([6]), 2118.2469166742576)
(array([1]), 1517.9245699309304)
(array([7]), 2103.0385160524283)
(array([0]), 3070.657584296888)
(array([9]), 2980.219958325224)
(array([7]), 2513.1329053593645)
(array([1]), 1951.3638820066337)
(array([2]), 2281.048881545505)
(array([8]), 2254.819726718746)
(array([4]), 2043.696650679841)
(array([4]), 2431.806735741967)
(array([6]), 2303.574830562272)
(array([1]), 1672.642520086106)
(array([8]), 2748.4830361492136)
(array([3]), 2315.7461000722856)
(array([0]), 2778.998740553871)
(array([8]), 2636.5731546839356)
(array([8]), 2336.889599446238)
(array([4]), 2289.5691734472666)
(array([6]), 2090.2267819545323)
(array([0]), 2991.376606179837)
(array([0]), 2804.7019

(array([1]), 2051.9471240750822)
(array([5]), 2483.524712983545)
(array([1]), 1719.7584132662355)
(array([1]), 1752.4006391233713)
(array([2]), 2110.549217620854)
(array([9]), 3037.3746887731845)
(array([4]), 2314.434056092331)
(array([2]), 3011.6030614939946)
(array([8]), 2390.5760811988393)
(array([2]), 2737.0051150847344)
(array([3]), 2249.838438643984)
(array([3]), 2339.3477723502333)
(array([4]), 2540.945886869691)
(array([1]), 1654.6301701588786)
(array([0]), 2596.6778775966804)
(array([0]), 3128.114927556211)
(array([6]), 2356.8315595307186)
(array([4]), 2122.970560323435)
(array([9]), 2548.3006102106556)
(array([2]), 2189.818485628432)
(array([7]), 1917.9676743887005)
(array([2]), 1936.276323255542)
(array([4]), 2491.6191522782933)
(array([1]), 1712.3644471899083)
(array([5]), 2677.64392703735)
(array([1]), 1775.8780926628945)
(array([0]), 2647.4693577074695)
(array([7]), 1975.9114352622184)
(array([1]), 1583.6609485619074)
(array([6]), 2417.480506643228)
(array([8]), 1921.3261

(array([3]), 2451.2686511274114)
(array([9]), 1923.0270408915212)
(array([9]), 2268.59119278904)
(array([1]), 1946.6622716845366)
(array([8]), 2449.7448846767697)
(array([0]), 2659.0763433944503)
(array([4]), 2179.206277523998)
(array([2]), 2199.3294432621956)
(array([8]), 2110.5686437545687)
(array([1]), 1583.8266950648356)
(array([7]), 2389.4300575660295)
(array([1]), 1627.963144545969)
(array([8]), 2152.7800630812244)
(array([5]), 2042.4201330774233)
(array([1]), 1317.9609250656865)
(array([8]), 1943.4206955777743)
(array([7]), 2030.2285585618188)
(array([7]), 2822.90417832416)
(array([1]), 1771.182938038869)
(array([4]), 2571.1837740620563)
(array([7]), 2286.5156898652585)
(array([9]), 2732.885471438567)
(array([9]), 1756.0461269568063)
(array([5]), 2336.4475170651704)
(array([4]), 2044.6327298563915)
(array([4]), 1924.5994388443535)
(array([5]), 2231.8263821363885)
(array([6]), 1982.0824907152578)
(array([0]), 2714.2903308231416)
(array([7]), 2293.378294132915)
(array([1]), 1377.6

(array([9]), 2019.7420627396955)
(array([0]), 2563.119583632414)
(array([8]), 1957.9425425686015)
(array([3]), 2754.6166702465152)
(array([7]), 1770.179086985269)
(array([6]), 3180.597742563495)
(array([8]), 1992.2823595063026)
(array([0]), 2723.805242670628)
(array([3]), 2387.266847254408)
(array([8]), 2122.48627792973)
(array([8]), 2192.3434949843054)
(array([2]), 2523.1672556531007)
(array([9]), 1886.2603213766652)
(array([1]), 1779.3018293701605)
(array([5]), 2755.578886549975)
(array([2]), 2476.616038064843)
(array([7]), 2630.363663070185)
(array([1]), 1754.1225726841326)
(array([6]), 2813.332365718633)
(array([4]), 2416.6694022973024)
(array([6]), 2309.0993915377485)
(array([4]), 2774.2393552107214)
(array([9]), 1914.7824941752522)
(array([5]), 2290.254789319302)
(array([6]), 2490.9500195708465)
(array([8]), 2505.291400216749)
(array([0]), 1844.0694130102586)
(array([1]), 1805.014958386772)
(array([6]), 2192.3441791835517)
(array([3]), 2283.1274603052716)
(array([2]), 1737.284662

(array([3]), 2718.6290662758684)
(array([8]), 2103.407473600871)
(array([0]), 2579.9445730480334)
(array([1]), 1743.015490464729)
(array([3]), 2009.4479341351446)
(array([6]), 2177.526808101338)
(array([2]), 2033.2186306445255)
(array([8]), 1909.6096459747998)
(array([8]), 2160.984035109931)
(array([7]), 1906.9197675833138)
(array([2]), 2195.7531737424406)
(array([6]), 3033.5828651942243)
(array([0]), 2855.867643991927)
(array([2]), 2283.5586263549267)
(array([1]), 1856.915183846586)
(array([3]), 2442.954768308247)
(array([6]), 2478.831176179612)
(array([8]), 2415.1681100908895)
(array([1]), 1645.2850816803755)
(array([0]), 2965.5250799816213)
(array([1]), 1830.0193988042859)
(array([5]), 2276.356299000664)
(array([7]), 2358.8938085467094)
(array([8]), 1975.6312915116525)
(array([7]), 2262.4922099313403)
(array([4]), 2527.14384236434)
(array([9]), 1689.7319314021381)
(array([1]), 1444.818327679989)
(array([1]), 1694.8923269635743)
(array([6]), 2751.3369477401347)
(array([8]), 2037.4071

(array([3]), 1913.9380867729237)
(array([1]), 1586.06935535619)
(array([6]), 2611.5041642700858)
(array([2]), 2293.7135828171745)
(array([9]), 2396.515178337079)
(array([3]), 2179.310211970751)
(array([0]), 2488.3271489094836)
(array([4]), 1892.9601157974776)
(array([2]), 2609.1260989074485)
(array([6]), 2571.3930076905785)
(array([7]), 2677.259419630455)
(array([3]), 2070.14951150877)
(array([6]), 2661.1745527116404)
(array([2]), 2811.2904510206695)
(array([7]), 2220.1213930774147)
(array([1]), 1745.2598660371468)
(array([2]), 2645.3689723741754)
(array([2]), 2287.6042052767784)
(array([6]), 3133.5155975357775)
(array([6]), 2009.200836153519)
(array([2]), 2414.5616579412504)
(array([8]), 2397.851329836777)
(array([3]), 2110.855987508385)
(array([5]), 1831.2258189529766)
(array([9]), 1956.3632075869757)
(array([0]), 2721.972262900561)
(array([8]), 2111.2389727361515)
(array([3]), 2476.905932812145)
(array([3]), 2244.39056315963)
(array([8]), 2627.5941467433663)
(array([4]), 2387.181392

(array([8]), 2110.115636641746)
(array([7]), 2532.4067603763815)
(array([1]), 1873.238906279709)
(array([3]), 2558.165944578264)
(array([0]), 1975.0665811561898)
(array([8]), 2490.965074022516)
(array([7]), 1731.80224044202)
(array([4]), 2029.0584023137433)
(array([1]), 1594.331207748252)
(array([1]), 1657.3294784079599)
(array([8]), 2432.670549005763)
(array([0]), 2681.864090516147)
(array([3]), 2502.037769499094)
(array([4]), 2592.7022582626028)
(array([9]), 2226.389229222959)
(array([9]), 2182.4642036010578)
(array([6]), 3116.3692014907347)
(array([7]), 1616.6901372866726)
(array([9]), 2248.368741999408)
(array([6]), 2648.7823617654963)
(array([3]), 2156.5998701659983)
(array([9]), 2064.1019839145547)
(array([5]), 2038.7265633232917)
(array([8]), 3024.620967989212)
(array([3]), 2829.5886626857973)
(array([7]), 1721.6056459015228)
(array([9]), 2122.585922878035)
(array([9]), 2917.288809836969)
(array([3]), 2057.9980563644854)
(array([9]), 2275.0382414368337)
(array([6]), 2309.7776949

In [9]:
#Sorting based on the second index of the list
list1.sort(key=lambda ele:ele[1])
list1

[(array([7]), 801.5846804923358),
 (array([7]), 815.1337313594622),
 (array([7]), 904.0608386607618),
 (array([7]), 915.217460497777),
 (array([7]), 1035.1304265646913),
 (array([7]), 1060.2942987680353),
 (array([7]), 1065.6082769948814),
 (array([7]), 1088.328994376241),
 (array([7]), 1107.8474624243177),
 (array([7]), 1108.4998872349965),
 (array([7]), 1114.7022023841166),
 (array([7]), 1127.8936120042529),
 (array([7]), 1129.9238912422377),
 (array([7]), 1130.8377425607973),
 (array([1]), 1136.8412378164332),
 (array([7]), 1142.3944152524557),
 (array([7]), 1167.6108084460336),
 (array([7]), 1169.8119506997696),
 (array([7]), 1172.3045679344596),
 (array([1]), 1181.0491099018702),
 (array([1]), 1185.0358644361781),
 (array([7]), 1188.5655219633454),
 (array([7]), 1192.454611295541),
 (array([1]), 1209.5449557581562),
 (array([1]), 1210.8319453995257),
 (array([1]), 1213.7759266025998),
 (array([7]), 1225.3069003315047),
 (array([1]), 1225.4015668343175),
 (array([1]), 1233.52584083

In [24]:
k=5
neighbors = []
for i in range(k):
    neighbors.append(list1[i][0])
    
neighbors

[array([7]), array([7]), array([7]), array([7]), array([7])]

In [25]:
output_values = [row[-1] for row in neighbors]
prediction = max(set(output_values), key=output_values.count)
print('Predicted class is : %s' % (prediction))

Predicted class is : 7
